# Generated by Django 3.2.16 on 2023-08-24 10:49

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=app.models.get_file_path, variations={'thumb': {'crop': True, 'height': 768, 'width': 1024}}, verbose_name='Imagem')),
                ('intro', models.TextField(max_length=250, verbose_name='Introdução')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
                ('bio', models.TextField(max_length=300, verbose_name='Bio')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to=app.models.get_file_path, variations={'thumb': {'crop': True, 'height': 600, 'width': 600}}, verbose_name='Foto')),
                ('linkedin', models.CharField(default='#', max_length=100, verbose_name='Linkedin')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo', verbose_name='Cargo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['-criado'],
            },
        ),
    ]
